### ISSUE TITLE
AttributeError: 'module' object has no attribute 'revision'

### ISSUE THREAD

**Issue by JimyRyan** [etianen/django-reversion#469]
I try to install the Django CMS 3.2 from Aldryn (https://github.com/aldryn/aldryn-django-cms), but when I launch the development web server, I have the error bellow : 

```AttributeError: 'module' object has no attribute 'revision```

I also try to reproduce this error outside the CMS addons ecosystem, so I execute this command : 

**(Python-2.7.10)[root@localhost Desktop]# python -c 'import reversion; print reversion.revisions.__version__'**

The error is look like the same : 

```Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'revisions'
(Python-2.7.10)[root@localhost Desktop]# python -c 'import reversion; print reversion.revisions.__version__'```

I'm using Python 2.7.10, Django 1.8.7, Django CMS 3.2, PostgreSQL 9.2

**Comment by etianen** [comment]
It looks like Django CMS doesn't specify a version requirement for
Django-reversion, so is pulling in the latest release, which contains
backwards-incompatible changes.

You could install Django-reversion 1.9.3 manually, which will fix the
issues for now, but won't work in Django 1.9

I'd also raise this issue on Django-CMS, pointing out that they need to
update their imports as documented in the Django-reversion release notes.

**Comment by SaeX** [comment]
FYI I'm getting `AttributeError: 'module' object has no attribute 'register'` as well once I update to Django 1.9.
I'm **not** using Django CMS though. 
Using django-reversion with the `reversion.middleware.RevisionMiddleware` middleware and `reversion.register(Model)` after every model definition.

Reverting to Django 1.8 fixes the issue.

**Comment by JimyRyan** [comment]
I have try using Django 1.8.7 and django-revision 1.9.3 : that did not change anything for me :(

**Comment by etianen** [comment]
Please read the changelog for the latest release. It'll tell you how to fix
your code.

https://github.com/etianen/django-reversion/blob/master/CHANGELOG.md

**Comment by SaeX** [comment]
Thanks, does fix my code indeed.

**Comment by JimyRyan** [comment]
Thanks for your fast response ! My trouble is now solved :)

Have an nice night.
